# Generated by Django 3.2.20 on 2023-07-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('altername', models.CharField(blank=True, max_length=255, null=True)),
                ('people', models.CharField(blank=True, max_length=255, null=True)),
                ('infectivity', models.IntegerField()),
                ('under_insurance', models.IntegerField()),
            ],
            options={
                'db_table': 'disease',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adverse_reaction', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medicine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(max_length=255)),
                ('part', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'symptoms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'treatments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.disease')),
                ('treament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.treatments')),
            ],
            options={
                'db_table': 'disease_treatment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.symptoms')),
            ],
            options={
                'db_table': 'disease_symptom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.disease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.medicine')),
            ],
            options={
                'db_table': 'disease_medicine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseDepartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.department')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymedicine.disease')),
            ],
            options={
                'db_table': 'disease_department',
                'managed': True,
            },
        ),
    ]
