# Generated by Django 3.2.20 on 2023-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=32)),
                ('part', models.CharField(max_length=32)),
                ('disease', models.ManyToManyField(to='disease.Disease')),
            ],
        ),
    ]
