# Generated by Django 3.2.20 on 2023-07-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_department_drug_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='disease',
            field=models.ManyToManyField(to='disease.Disease'),
        ),
    ]
